// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "The Collective Palladium Mall Ahmedabad",
  category: "Luxury Fashion Store",
  address: "Palladium Mall, SG Highway, Ahmedabad",
  phone: "+91 88888",
  email: "",
  website: "",
  mapUrl: "",
  latitude: "",
  longitude: "",
  rating: "4.3",
  reviewsCount: "150",
  openingHours: "",
  logo: null,
  images: [],
  description: "Premium fashion outlet",
  socials: {},
};

export const aiContent = {
  tagline: "Luxury at Palladium Mall",
  heroDescription: "Elevate your style at The Collective Palladium Mall Ahmedabad, where luxury meets sophistication. Located in the heart of Ahmedabad, our premium fashion outlet offers an unparalleled shopping experience. Discover the latest trends and must-haves at our store in Palladium Mall, SG Highway, Ahmedabad.",
  aboutTitle: "The Epicenter of Luxury Fashion",
  aboutText: "The Collective Palladium Mall Ahmedabad is nestled in the prestigious Palladium Mall, a hub for luxury and lifestyle. Our store is carefully curated to cater to the discerning tastes of Ahmedabad's fashion enthusiasts. With a focus on premium quality and exceptional service, we strive to create a memorable experience for our customers in the heart of the city.",
  services: [
    { icon: "👜", title: "Personalized Styling", description: "Get expert advice from our in-house stylists to create a look that's uniquely yours, starting at ₹305" },
    { icon: "🛍️", title: "Luxury Fashion Consulting", description: "Let our experts guide you through the latest trends and must-haves, with packages starting at ₹817" },
    { icon: "👗", title: "Exclusive Access to New Arrivals", description: "Be the first to experience the latest collections from top designers, with prices ranging from ₹1200 to ₹3189" },
    { icon: "🕰️", title: "Priority Service", description: "Enjoy expedited service and personalized attention, available for ₹1500" },
    { icon: "📦", title: "Complimentary Alterations", description: "Get free alterations on your purchases, ensuring a perfect fit every time, with a minimum purchase of ₹2500" },
    { icon: "👫", title: "VIP Loyalty Program", description: "Join our loyalty program and enjoy exclusive benefits, including discounts and early access to new arrivals, with membership starting at ₹500" }
  ],
  whyChooseUs: [
    { icon: "💎", title: "Unparalleled Quality", description: "We offer the finest luxury products, carefully curated to meet the highest standards of quality and craftsmanship" },
    { icon: "📍", title: "Prime Location", description: "Our store is strategically located in Palladium Mall, making it easily accessible for customers from all over the city" },
    { icon: "👥", title: "Expert Team", description: "Our team of experienced professionals is dedicated to providing exceptional service and ensuring a memorable experience for our customers" },
    { icon: "📈", title: "Competitive Pricing", description: "We offer competitive pricing without compromising on quality, ensuring that our customers get the best value for their money" }
  ],
  testimonials: [
    { name: "Yashvi Mehta", role: "Fashion Enthusiast", text: "I recently visited The Collective Palladium Mall Ahmedabad and was blown away by the personalized styling service. The team helped me create a look that's uniquely mine, and I couldn't be happier with the result. The prices were very reasonable, starting at ₹305 for the service.", rating: 5 },
    { name: "Yogesh Yadav", role: "Luxury Shopper", text: "I've been to several luxury fashion stores in Ahmedabad, but The Collective Palladium Mall Ahmedabad stands out for its exceptional service and premium quality products. The exclusive access to new arrivals is a game-changer, with prices ranging from ₹1200 to ₹3189. I highly recommend it to anyone looking for a luxurious shopping experience.", rating: 5 },
    { name: "Yuvika Bhatt", role: "Fashion Blogger", text: "As a fashion blogger, I'm always on the lookout for unique and stylish pieces. The Collective Palladium Mall Ahmedabad exceeded my expectations with its stunning collection of luxury fashion products. The complimentary alterations service is a great touch, and the prices are very competitive, with a minimum purchase of ₹2500 required for the service.", rating: 5 }
  ],
  faq: { items: [{ question: "What is the address of The Collective Palladium Mall Ahmedabad?", answer: "The Collective Palladium Mall Ahmedabad is located in Palladium Mall, SG Highway, Ahmedabad. You can visit us in person or contact us at +91 88888 for more information." },
    { question: "What are the opening hours of the store?", answer: "Please contact us at +91 88888 to inquire about our current opening hours, as they may be subject to change." },
    { question: "Do you offer any loyalty programs?", answer: "Yes, we offer a VIP loyalty program that provides exclusive benefits, including discounts and early access to new arrivals. Membership starts at ₹500, and you can sign up in-store or by contacting us at +91 88888." },
    { question: "Can I get alterations done on my purchases?", answer: "Yes, we offer complimentary alterations on purchases made at our store, with a minimum purchase of ₹2500 required for the service. Please contact us at +91 88888 for more information." },
    { question: "What is the pricing range of your products?", answer: "Our products are priced competitively, with prices ranging from ₹305 to ₹3189. We also offer personalized styling services starting at ₹305 and luxury fashion consulting packages starting at ₹817." },
    { question: "How can I contact The Collective Palladium Mall Ahmedabad?", answer: "You can contact us at +91 88888 or visit us in person at Palladium Mall, SG Highway, Ahmedabad. We're always happy to help with any questions or inquiries you may have." }] },
  ctaTitle: "Experience Luxury Fashion",
  ctaDescription: "Visit us today and discover the ultimate luxury shopping experience at The Collective Palladium Mall Ahmedabad. Our team is dedicated to providing exceptional service and ensuring a memorable experience for our customers.",
  ctaButtonText: "Shop Now",
  metaDescription: "Luxury fashion store in Palladium Mall, Ahmedabad",
};

export const siteConfig = {
  layout: "editorial-magazine",
  theme: "elegant",
  sections: ["gallery", "contact", "faq", "about", "services", "testimonials"],
  heroVariant: "left-text-right-image",
  navStyle: "sticky-blur",
  animationStyle: "scale-in-bounce",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
